### ISSUE TITLE
commitの名前の表記を片方にする

### ISSUE THREAD

**Issue by y4ml** [y4ml/mottanLearning#12]
個人特定をさけるために、片方のみ表示するようにしたい
![image](https://user-images.githubusercontent.com/48861018/165870918-0faf0821-d04c-42ec-a978-b88fd6ebea20.png)

**Comment by mottanCopen** [comment]
これはどうすればいいのかな？

**Comment by y4ml** [comment]
> これはどうすればいいのかな？

宿題です。

**Comment by mottanCopen** [comment]
宿題にするほどの内容なのか...

**Comment by mottanCopen** [comment]
これでいいですか？

**Comment by y4ml** [comment]
頑張ったのでcloseします。
