### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mottanCopen** [y4ml/mottanLearning#5]
昨日インストールしたJDKはOracleなの？
インストール手順が違ったから

**Comment by y4ml** [comment]
ターミナルでjava --versionと入力してみてください。
提供されているベンダーが異なる場合でもJDKに違いはないはずです。

**Comment by mottanCopen** [comment]
つまりは、どこのメーカーのJDKでもできることは同じってこと？

**Comment by y4ml** [comment]
YES

**Comment by mottanCopen** [comment]
にゃーるほど
